# Generated by Django 3.2.15 on 2022-09-24 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0005_alter_item_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bill',
            new_name='total',
        ),
    ]
