# Generated by Django 3.2.15 on 2022-09-24 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_drink'),
        ('confirmation', '0006_rename_bill_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='burger',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.burger'),
        ),
        migrations.AddField(
            model_name='item',
            name='drink',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.drink'),
        ),
        migrations.AddField(
            model_name='item',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6),
        ),
        migrations.AddField(
            model_name='item',
            name='side',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.side'),
        ),
    ]
