# Generated by Django 3.2.15 on 2022-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0008_delete_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
