# Generated by Django 3.2.15 on 2022-09-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confirmation', '0009_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.ManyToManyField(blank=True, to='confirmation.Order'),
        ),
    ]
