# Generated by Django 3.2.15 on 2022-09-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_sides'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sides',
            new_name='Side',
        ),
    ]
